name: Main

on:
  workflow_dispatch

jobs:
  main:
    name: Main
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        setup-action-version: [d8f656ed88025ca3bacdfb5d2d1363dd8943832f]
        
    runs-on: ${{ matrix.os }}
    steps:
    - name: Context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
    - name: Setup Snyk
      uses: snyk/actions/setup@${{ matrix.setup-action-version }}
    - run: |
        which snyk
        snyk --help
